server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/rentals

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # Se seus controllers nos serviços estão mapeados com /api/users e /api/listings:
        - id: users
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: listings
          uri: http://localhost:8083
          predicates:
            - Path=/api/listings/**
