server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/rentals
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8080
          predicates:
            - Path=/hello

