version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  mongo-init-replica:
    image: mongo:7
    depends_on: [mongo]
    entrypoint: ["bash","-lc","sleep 3 && mongosh --host mongo:27017 --eval 'rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongo:27017\"}]})' || true"]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command:
      - start-dev
      - --http-port=8081
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    volumes:
      - ../keycloak/realm-rentals.json:/opt/keycloak/data/import/realm-rentals.json:ro

volumes:
  mongo_data:
